export interface LanguageDefinition {
  code: string;
  englishName: string;
}

export const LANGUAGE_OPTIONS: readonly LanguageDefinition[] = [
  { code: 'af', englishName: 'Afrikaans' },
  { code: 'sq', englishName: 'Albanian' },
  { code: 'am', englishName: 'Amharic' },
  { code: 'ar', englishName: 'Arabic' },
  { code: 'hy', englishName: 'Armenian' },
  { code: 'as', englishName: 'Assamese' },
  { code: 'ay', englishName: 'Aymara' },
  { code: 'az', englishName: 'Azerbaijani' },
  { code: 'bm', englishName: 'Bambara' },
  { code: 'eu', englishName: 'Basque' },
  { code: 'be', englishName: 'Belarusian' },
  { code: 'bn', englishName: 'Bengali' },
  { code: 'bho', englishName: 'Bhojpuri' },
  { code: 'bs', englishName: 'Bosnian' },
  { code: 'bg', englishName: 'Bulgarian' },
  { code: 'ca', englishName: 'Catalan' },
  { code: 'ceb', englishName: 'Cebuano' },
  { code: 'ny', englishName: 'Chichewa' },
  { code: 'zh', englishName: 'Chinese (Simplified)' },
  { code: 'zh-TW', englishName: 'Chinese (Traditional)' },
  { code: 'co', englishName: 'Corsican' },
  { code: 'hr', englishName: 'Croatian' },
  { code: 'cs', englishName: 'Czech' },
  { code: 'da', englishName: 'Danish' },
  { code: 'dv', englishName: 'Dhivehi' },
  { code: 'doi', englishName: 'Dogri' },
  { code: 'nl', englishName: 'Dutch' },
  { code: 'en', englishName: 'English' },
  { code: 'eo', englishName: 'Esperanto' },
  { code: 'et', englishName: 'Estonian' },
  { code: 'ee', englishName: 'Ewe' },
  { code: 'tl', englishName: 'Filipino' },
  { code: 'fi', englishName: 'Finnish' },
  { code: 'fr', englishName: 'French' },
  { code: 'fy', englishName: 'Frisian' },
  { code: 'gl', englishName: 'Galician' },
  { code: 'ka', englishName: 'Georgian' },
  { code: 'de', englishName: 'German' },
  { code: 'el', englishName: 'Greek' },
  { code: 'gn', englishName: 'Guarani' },
  { code: 'gu', englishName: 'Gujarati' },
  { code: 'ht', englishName: 'Haitian Creole' },
  { code: 'ha', englishName: 'Hausa' },
  { code: 'haw', englishName: 'Hawaiian' },
  { code: 'he', englishName: 'Hebrew' },
  { code: 'hi', englishName: 'Hindi' },
  { code: 'hmn', englishName: 'Hmong' },
  { code: 'hu', englishName: 'Hungarian' },
  { code: 'is', englishName: 'Icelandic' },
  { code: 'ig', englishName: 'Igbo' },
  { code: 'ilo', englishName: 'Ilocano' },
  { code: 'id', englishName: 'Indonesian' },
  { code: 'ga', englishName: 'Irish' },
  { code: 'it', englishName: 'Italian' },
  { code: 'ja', englishName: 'Japanese' },
  { code: 'jv', englishName: 'Javanese' },
  { code: 'kn', englishName: 'Kannada' },
  { code: 'kk', englishName: 'Kazakh' },
  { code: 'km', englishName: 'Khmer' },
  { code: 'rw', englishName: 'Kinyarwanda' },
  { code: 'gom', englishName: 'Konkani' },
  { code: 'ko', englishName: 'Korean' },
  { code: 'kri', englishName: 'Krio' },
  { code: 'ku', englishName: 'Kurdish (Kurmanji)' },
  { code: 'ckb', englishName: 'Kurdish (Sorani)' },
  { code: 'ky', englishName: 'Kyrgyz' },
  { code: 'lo', englishName: 'Lao' },
  { code: 'la', englishName: 'Latin' },
  { code: 'lv', englishName: 'Latvian' },
  { code: 'ln', englishName: 'Lingala' },
  { code: 'lt', englishName: 'Lithuanian' },
  { code: 'lg', englishName: 'Luganda' },
  { code: 'lb', englishName: 'Luxembourgish' },
  { code: 'mk', englishName: 'Macedonian' },
  { code: 'mai', englishName: 'Maithili' },
  { code: 'mg', englishName: 'Malagasy' },
  { code: 'ms', englishName: 'Malay' },
  { code: 'ml', englishName: 'Malayalam' },
  { code: 'mt', englishName: 'Maltese' },
  { code: 'mi', englishName: 'Maori' },
  { code: 'mr', englishName: 'Marathi' },
  { code: 'mni-Mtei', englishName: 'Meiteilon (Manipuri)' },
  { code: 'lus', englishName: 'Mizo' },
  { code: 'mn', englishName: 'Mongolian' },
  { code: 'my', englishName: 'Myanmar (Burmese)' },
  { code: 'ne', englishName: 'Nepali' },
  { code: 'no', englishName: 'Norwegian' },
  { code: 'or', englishName: 'Odia (Oriya)' },
  { code: 'om', englishName: 'Oromo' },
  { code: 'ps', englishName: 'Pashto' },
  { code: 'fa', englishName: 'Persian' },
  { code: 'pl', englishName: 'Polish' },
  { code: 'pt', englishName: 'Portuguese' },
  { code: 'pa', englishName: 'Punjabi' },
  { code: 'qu', englishName: 'Quechua' },
  { code: 'ro', englishName: 'Romanian' },
  { code: 'ru', englishName: 'Russian' },
  { code: 'sm', englishName: 'Samoan' },
  { code: 'sa', englishName: 'Sanskrit' },
  { code: 'gd', englishName: 'Scots Gaelic' },
  { code: 'nso', englishName: 'Sepedi' },
  { code: 'sr', englishName: 'Serbian' },
  { code: 'st', englishName: 'Sesotho' },
  { code: 'sn', englishName: 'Shona' },
  { code: 'sd', englishName: 'Sindhi' },
  { code: 'si', englishName: 'Sinhala' },
  { code: 'sk', englishName: 'Slovak' },
  { code: 'sl', englishName: 'Slovenian' },
  { code: 'so', englishName: 'Somali' },
  { code: 'es', englishName: 'Spanish' },
  { code: 'su', englishName: 'Sundanese' },
  { code: 'sw', englishName: 'Swahili' },
  { code: 'sv', englishName: 'Swedish' },
  { code: 'tg', englishName: 'Tajik' },
  { code: 'ta', englishName: 'Tamil' },
  { code: 'tt', englishName: 'Tatar' },
  { code: 'te', englishName: 'Telugu' },
  { code: 'th', englishName: 'Thai' },
  { code: 'ti', englishName: 'Tigrinya' },
  { code: 'ts', englishName: 'Tsonga' },
  { code: 'tr', englishName: 'Turkish' },
  { code: 'tk', englishName: 'Turkmen' },
  { code: 'ak', englishName: 'Twi (Akan)' },
  { code: 'uk', englishName: 'Ukrainian' },
  { code: 'ur', englishName: 'Urdu' },
  { code: 'ug', englishName: 'Uyghur' },
  { code: 'uz', englishName: 'Uzbek' },
  { code: 'vi', englishName: 'Vietnamese' },
  { code: 'cy', englishName: 'Welsh' },
  { code: 'xh', englishName: 'Xhosa' },
  { code: 'yi', englishName: 'Yiddish' },
  { code: 'yo', englishName: 'Yoruba' },
  { code: 'zu', englishName: 'Zulu' }
] as const;

export type LanguageOption = typeof LANGUAGE_OPTIONS[number]['code'];
