import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const stylesDir = path.resolve(__dirname, '../src/styles');
const tokensJsonPath = path.join(stylesDir, 'tokens.json');
const tokensCssPath = path.join(stylesDir, 'tokens.css');
const tokensTsPath = path.join(stylesDir, 'tokens.ts');

const camelToKebab = (str) => str.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);

const prefixMap = {
  colors: '--color-',
  button: '--button-',
  apple: '--apple-',
  radius: '--radius-',
  spacing: '--spacing-',
  fontSizes: '--font-size-',
  typography: '--font-',
  shadows: '--shadow-',
  transitions: '--transition-',
};

export function buildTokens(inputJsonPath = tokensJsonPath) {
  const raw = fs.readFileSync(inputJsonPath, 'utf-8');
  const tokens = JSON.parse(raw);

  if (
    !tokens ||
    typeof tokens !== 'object' ||
    !tokens.theme?.light ||
    !tokens.theme?.dark ||
    !tokens.global
  ) {
    throw new Error(
      'Invalid tokens.json structure: missing theme.light, theme.dark, or global sections.'
    );
  }

  // 1. Build CSS
  let css = '/** Auto-generated by build-tokens.mjs. Do not edit directly. **/\n\n:root {\n';

  // Light theme sections
  for (const [section, entries] of Object.entries(tokens.theme.light)) {
    const prefix = prefixMap[section];
    if (!prefix) {
      throw new Error(
        `Unknown token section "${section}". Expected one of: ${Object.keys(prefixMap).join(', ')}`
      );
    }
    for (const [k, v] of Object.entries(entries)) {
      css += `  ${prefix}${camelToKebab(k)}: ${v};\n`;
    }
  }

  // Global sections
  for (const [section, entries] of Object.entries(tokens.global)) {
    const prefix = prefixMap[section];
    if (!prefix) {
      throw new Error(
        `Unknown token section "${section}". Expected one of: ${Object.keys(prefixMap).join(', ')}`
      );
    }
    for (const [k, v] of Object.entries(entries)) {
      css += `  ${prefix}${camelToKebab(k)}: ${v};\n`;
    }
  }

  // Compatibility & shorthand aliases
  css += '\n  /* Compatibility & Shorthand Aliases */\n';
  css += '  --bg-primary: var(--color-bg-primary);\n';
  css += '  --bg-secondary: var(--color-bg-secondary);\n';
  css += '  --text-primary: var(--color-text-primary);\n';
  css += '  --border: var(--color-border);\n';
  css += '  --color-primary: var(--color-accent-primary);\n';
  css += '  --color-text-main: var(--color-text-primary);\n';
  css += '}\n\n:root[data-theme="dark"] {\n';

  // Dark theme overrides
  for (const [section, entries] of Object.entries(tokens.theme.dark)) {
    const prefix = prefixMap[section];
    if (!prefix) {
      throw new Error(
        `Unknown token section "${section}". Expected one of: ${Object.keys(prefixMap).join(', ')}`
      );
    }
    for (const [k, v] of Object.entries(entries)) {
      css += `  ${prefix}${camelToKebab(k)}: ${v};\n`;
    }
  }
  css += '}\n';

  // 2. Build TS objects
  const themeTokens = {};
  const lightTokens = {};
  const darkTokens = {};

  // Initialize sections
  for (const section of Object.keys(prefixMap)) {
    themeTokens[section] = {};
    lightTokens[section] = {};
    darkTokens[section] = {};
  }

  // Populate theme light & dark
  for (const section of Object.keys(tokens.theme.light)) {
    const prefix = prefixMap[section];
    for (const k of Object.keys(tokens.theme.light[section])) {
      themeTokens[section][k] = `var(${prefix}${camelToKebab(k)})`;
      lightTokens[section][k] = tokens.theme.light[section][k];
      darkTokens[section][k] = tokens.theme.dark[section]?.[k] ?? tokens.theme.light[section][k];
    }
  }

  // Populate global
  for (const section of Object.keys(tokens.global)) {
    const prefix = prefixMap[section];
    for (const [k, v] of Object.entries(tokens.global[section])) {
      themeTokens[section][k] = `var(${prefix}${camelToKebab(k)})`;
      lightTokens[section][k] = v;
      darkTokens[section][k] = v;
    }
  }

  const tsContent = `/** Auto-generated by build-tokens.mjs. Do not edit directly. */

export const themeTokens = ${JSON.stringify(themeTokens, null, 2)} as const;

export type ThemeTokens = typeof themeTokens;

export const lightTokens = ${JSON.stringify(lightTokens, null, 2)} as const;

export const darkTokens = ${JSON.stringify(darkTokens, null, 2)} as const;

export type RawThemeTokens = typeof lightTokens;
`;

  // Write if modified
  const currentCss = fs.existsSync(tokensCssPath) ? fs.readFileSync(tokensCssPath, 'utf-8') : '';
  if (currentCss !== css) {
    fs.writeFileSync(tokensCssPath, css, 'utf-8');
  }

  const currentTs = fs.existsSync(tokensTsPath) ? fs.readFileSync(tokensTsPath, 'utf-8') : '';
  if (currentTs !== tsContent) {
    fs.writeFileSync(tokensTsPath, tsContent, 'utf-8');
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildTokens();
}
