type DeepValueOf<T> = T extends string
  ? T
  : {
      [K in keyof T]: DeepValueOf<T[K]>;
    }[keyof T];

export const TauriCommand = {
  app: {
    extractTarBz2: 'extract_tar_bz2',
    downloadFile: 'download_file',
    cancelDownload: 'cancel_download',
    openLogFolder: 'open_log_folder',
    getModelCatalogSnapshot: 'get_model_catalog_snapshot',
    resolveModelCatalogSelectedIds: 'resolve_model_catalog_selected_ids',
    getDiagnosticsCoreSnapshot: 'get_diagnostics_core_snapshot',
    loadAppConfig: 'load_app_config',
    saveAppConfig: 'save_app_config',
    getAppSetting: 'get_app_setting',
    setAppSetting: 'set_app_setting',
    migrateAppConfig: 'migrate_app_config',
    resolveEffectiveConfig: 'resolve_effective_config',
    getRuntimeEnvironmentStatus: 'get_runtime_environment_status',
    getAsrRuntimeMetrics: 'get_asr_runtime_metrics',
    getPathStatuses: 'get_path_statuses',
    hasActiveDownloads: 'has_active_downloads',
    forceExit: 'force_exit',
    updateTrayMenu: 'update_tray_menu',
    setMinimizeToTray: 'set_minimize_to_tray',
    setLogLevel: 'set_log_level',
    checkMediaFormats: 'check_media_formats',
  },
  audio: {
    setSystemAudioMute: 'set_system_audio_mute',
    getSystemAudioDevices: 'get_system_audio_devices',
    startSystemAudioCapture: 'start_system_audio_capture',
    stopSystemAudioCapture: 'stop_system_audio_capture',
    setSystemAudioCapturePaused: 'set_system_audio_capture_paused',
    setMicrophoneBoost: 'set_microphone_boost',
    getMicrophoneDevices: 'get_microphone_devices',
    startMicrophoneCapture: 'start_microphone_capture',
    stopMicrophoneCapture: 'stop_microphone_capture',
    setMicrophoneCapturePaused: 'set_microphone_capture_paused',
  },
  history: {
    listItems: 'history_list_items',
    createLiveDraft: 'history_create_live_draft',
    completeLiveDraft: 'history_complete_live_draft',
    saveRecording: 'history_save_recording',
    saveImportedFile: 'history_save_imported_file',
    deleteItems: 'history_delete_items',
    trashItems: 'history_trash_items',
    restoreItems: 'history_restore_items',
    purgeItems: 'history_purge_items',
    loadTranscript: 'history_load_transcript',
    updateTranscript: 'history_update_transcript',
    createTranscriptSnapshot: 'history_create_transcript_snapshot',
    listTranscriptSnapshots: 'history_list_transcript_snapshots',
    loadTranscriptSnapshot: 'history_load_transcript_snapshot',
    buildTranscriptDiff: 'history_build_transcript_diff',
    restoreTranscriptDiffRows: 'history_restore_transcript_diff_rows',
    updateItemMeta: 'history_update_item_meta',
    updateProjectAssignments: 'history_update_project_assignments',
    reassignProject: 'history_reassign_project',
    updateTagAssignments: 'history_update_tag_assignments',
    replaceTagAssignments: 'history_replace_tag_assignments',
    loadSummary: 'history_load_summary',
    saveSummary: 'history_save_summary',
    deleteSummary: 'history_delete_summary',
    resolveAudioPath: 'history_resolve_audio_path',
    previewAudioCleanup: 'history_preview_audio_cleanup',
    cleanupAudio: 'history_cleanup_audio',
    queryWorkspace: 'history_query_workspace',
    openFolder: 'history_open_folder',
  },
  storage: {
    getUsageSnapshot: 'storage_get_usage_snapshot',
    clearWebviewBrowsingData: 'storage_clear_webview_browsing_data',
  },
  dashboard: {
    getSnapshot: 'get_dashboard_snapshot',
  },
  export: {
    transcriptFile: 'export_transcript_file',
  },
  project: {
    list: 'project_list',
    saveAll: 'project_save_all',
    create: 'project_create',
    update: 'project_update',
    delete: 'project_delete',
    reorder: 'project_reorder',
    getActiveId: 'project_get_active_id',
    setActiveId: 'project_set_active_id',
  },
  tag: {
    list: 'tag_list',
    saveAll: 'tag_save_all',
    create: 'tag_create',
    update: 'tag_update',
    delete: 'tag_delete',
    reorder: 'tag_reorder',
    getActiveId: 'tag_get_active_id',
    setActiveId: 'tag_set_active_id',
  },
  automationRepository: {
    loadState: 'automation_load_repository_state',
    persistRules: 'automation_persist_rules',
    persistProcessedEntries: 'automation_persist_processed_entries',
    persistState: 'automation_persist_repository_state',
    validateActivation: 'automation_validate_rule_activation',
  },
  llmUsage: {
    ensureStorage: 'llm_usage_ensure_storage',
    readRaw: 'llm_usage_read_raw',
    replaceRaw: 'llm_usage_replace_raw',
  },
  llm: {
    complete: 'complete_llm',
    describeModel: 'describe_llm_model',
    generateText: 'generate_llm_text',
    listModels: 'list_llm_models',
    polishTranscriptSegments: 'polish_transcript_segments',
    runTranscriptJob: 'run_transcript_llm_job',
    summarizeTranscript: 'summarize_transcript',
    translateTranscriptSegments: 'translate_transcript_segments',
  },
  recognizer: {
    init: 'init_recognizer',
    start: 'start_recognizer',
    stop: 'stop_recognizer',
    flush: 'flush_recognizer',
    feedAudioChunk: 'feed_audio_chunk',
    processBatchFile: 'process_batch_file',
  },
  recovery: {
    loadSnapshot: 'recovery_load_snapshot',
    saveSnapshot: 'recovery_save_snapshot',
    persistQueueSnapshot: 'recovery_persist_queue_snapshot',
  },
  taskLedger: {
    loadSnapshot: 'task_ledger_load_snapshot',
    upsertTask: 'task_ledger_upsert_task',
    patchTask: 'task_ledger_patch_task',
    removeTask: 'task_ledger_remove_task',
    clearResolved: 'task_ledger_clear_resolved',
  },
  automation: {
    replaceRuntimeRules: 'replace_automation_runtime_rules',
    scanRuntimeRule: 'scan_automation_runtime_rule',
    collectRuntimeRulePaths: 'collect_automation_runtime_rule_paths',
  },
  backup: {
    exportArchive: 'export_backup_archive',
    prepareImport: 'prepare_backup_import',
    applyPreparedImport: 'apply_prepared_history_import',
    disposePreparedImport: 'dispose_prepared_backup_import',
  },
  sync: {
    getStatus: 'sync_get_status',
    testProvider: 'sync_test_provider',
    testWebDavProvider: 'sync_test_webdav_provider',
    listLegacyBackups: 'sync_list_legacy_backups',
    prepareLegacyBackupImport: 'sync_prepare_legacy_backup_import',
    createVault: 'sync_create_vault',
    previewJoin: 'sync_preview_join',
    joinVault: 'sync_join_vault',
    unlock: 'sync_unlock',
    unlockWithRecovery: 'sync_unlock_with_recovery',
    lock: 'sync_lock',
    setPaused: 'sync_set_paused',
    disconnect: 'sync_disconnect',
    runNow: 'sync_run_now',
    changePreset: 'sync_change_preset',
    changeMasterPassword: 'sync_change_master_password',
    generateRecoveryKey: 'sync_generate_recovery_key',
    listConflicts: 'sync_list_conflicts',
    getConflict: 'sync_get_conflict',
    resolveConflict: 'sync_resolve_conflict',
  },
  speaker: {
    annotateSegmentsFromFile: 'annotate_speaker_segments_from_file',
    importProfileSample: 'import_speaker_profile_sample',
    buildReviewSnapshot: 'build_speaker_review_snapshot',
    applyProfileToGroup: 'apply_speaker_profile_to_group',
    resetGroupToAnonymous: 'reset_speaker_group_to_anonymous',
    confirmGroupReview: 'confirm_speaker_group_review',
  },
  system: {
    setAuxWindowState: 'set_aux_window_state',
    getAuxWindowState: 'get_aux_window_state',
    clearAuxWindowState: 'clear_aux_window_state',
    injectText: 'inject_text',
    getMousePosition: 'get_mouse_position',
    getTextCursorPosition: 'get_text_cursor_position',
  },
  apiServer: {
    start: 'start_api_server',
    stop: 'stop_api_server',
    dashboardSnapshot: 'get_api_server_dashboard_snapshot',
  },
} as const;

export type TauriCommandName = DeepValueOf<typeof TauriCommand>;
