// This file has been generated by Tauri Specta. Do not edit this file manually.


/* Types */
export type BuiltinLlmProvider = BuiltinLlmProvider_Serialize | BuiltinLlmProvider_Deserialize;

export type BuiltinLlmProvider_Deserialize = "google_translate" | "google_translate_free" | "open_ai" | "open_ai_responses" | "azure_openai" | "anthropic" | "gemini" | "ollama" | "deep_seek" | "moonshot_ai" | "moonshot_cn" | "xiaomi" | "kimi" | "silicon_flow" | "qwen" | "qwen_portal" | "minimax_global" | "minimax_cn" | "openrouter" | "lm_studio" | "groq" | "x_ai" | "mistral_ai" | "perplexity" | "volcengine" | "chatglm" | "copilot" | "github_copilot" | "custom-openai-compatible" | "openai_compatible" | "open_ai_compatible";

export type BuiltinLlmProvider_Serialize = "google_translate" | "google_translate_free" | "open_ai" | "open_ai_responses" | "azure_openai" | "anthropic" | "gemini" | "ollama" | "deep_seek" | "moonshot_ai" | "moonshot_cn" | "xiaomi" | "kimi" | "silicon_flow" | "qwen" | "qwen_portal" | "minimax_global" | "minimax_cn" | "openrouter" | "lm_studio" | "groq" | "x_ai" | "mistral_ai" | "perplexity" | "volcengine" | "chatglm" | "copilot" | "custom-openai-compatible";

export type BuiltinPolishPresetId = "general" | "customer_service" | "meeting" | "interview" | "lecture" | "podcast";

export type BuiltinSummaryTemplateId = "general" | "meeting" | "lecture";

export type LlmProvider = LlmProvider_Serialize | LlmProvider_Deserialize;

export type LlmProvider_Deserialize = ({ Builtin: BuiltinLlmProvider_Deserialize }) & { Custom?: never } | ({ Custom: string }) & { Builtin?: never };

export type LlmProvider_Serialize = ({ Builtin: BuiltinLlmProvider_Serialize }) & { Custom?: never } | ({ Custom: string }) & { Builtin?: never };

export type LlmSegmentInput = {
	id: string,
	text: string,
};

export type LlmTaskChunkPayload<T> = {
	taskId: string,
	taskType: LlmTaskType,
	chunkIndex: number,
	totalChunks: number,
	items: T[],
};

export type LlmTaskProgressPayload = {
	taskId: string,
	taskType: LlmTaskType,
	completedChunks: number,
	totalChunks: number,
};

export type LlmTaskTextPayload = {
	taskId: string,
	taskType: LlmTaskType,
	text: string,
	delta: string,
	reset: boolean,
};

export type LlmTaskType = "polish" | "translate" | "summary";

export type PolishPresetId = ({ Builtin: BuiltinPolishPresetId }) & { Custom?: never } | ({ Custom: string }) & { Builtin?: never };

export type PolishedSegment = {
	id: string,
	text: string,
};

export type SummarySegmentInput = {
	id: string,
	text: string,
	start: number | null,
	end: number | null,
	isFinal: boolean,
};

export type SummaryTemplateId = ({ Builtin: BuiltinSummaryTemplateId }) & { Custom?: never } | ({ Custom: string }) & { Builtin?: never };

export type TranscriptSummaryResult = {
	templateId: string,
	content: string,
};

export type TranslatedSegment = {
	id: string,
	translation: string,
};
