// This file has been generated by Specta. Do not edit this file manually.
export type BuiltinLlmProvider = BuiltinLlmProvider_Serialize | BuiltinLlmProvider_Deserialize;

export type BuiltinLlmProvider_Deserialize = "google_translate" | "google_translate_free" | "open_ai" | "open_ai_responses" | "azure_openai" | "anthropic" | "gemini" | "ollama" | "deep_seek" | "moonshot_ai" | "moonshot_cn" | "xiaomi" | "kimi" | "silicon_flow" | "qwen" | "qwen_portal" | "minimax_global" | "minimax_cn" | "openrouter" | "lm_studio" | "groq" | "x_ai" | "mistral_ai" | "perplexity" | "volcengine" | "chatglm" | "copilot" | "github_copilot" | "custom-openai-compatible" | "openai_compatible" | "open_ai_compatible";

export type BuiltinLlmProvider_Serialize = "google_translate" | "google_translate_free" | "open_ai" | "open_ai_responses" | "azure_openai" | "anthropic" | "gemini" | "ollama" | "deep_seek" | "moonshot_ai" | "moonshot_cn" | "xiaomi" | "kimi" | "silicon_flow" | "qwen" | "qwen_portal" | "minimax_global" | "minimax_cn" | "openrouter" | "lm_studio" | "groq" | "x_ai" | "mistral_ai" | "perplexity" | "volcengine" | "chatglm" | "copilot" | "custom-openai-compatible";

export type BuiltinPolishPresetId = "general" | "customer_service" | "meeting" | "interview" | "lecture" | "podcast";

export type BuiltinSummaryTemplateId = "general" | "meeting" | "lecture";

export type ContentStats = ContentStats_Serialize | ContentStats_Deserialize;

export type ContentStats_Deserialize = {
	overview: OverviewStats_Deserialize,
	speakers: SpeakerStats | null,
};

export type ContentStats_Serialize = {
	overview: OverviewStats_Serialize,
	speakers: SpeakerStats | null,
};

export type ContentTrendPoint = {
	date: string,
	dateLabel: string,
	itemCount: number,
	itemCountDisplay: string,
	durationSeconds: number,
	durationDisplay: string,
};

export type DashboardSnapshotDomainModel = DashboardSnapshotDomainModel_Serialize | DashboardSnapshotDomainModel_Deserialize;

export type DashboardSnapshotDomainModel_Deserialize = {
	content: ContentStats_Deserialize,
	llmUsage: LlmUsageDashboardStats_Deserialize,
	generatedAt: string,
};

export type DashboardSnapshotDomainModel_Serialize = {
	content: ContentStats_Serialize,
	llmUsage: LlmUsageDashboardStats_Serialize,
	generatedAt: string,
};

export type DashboardUsageBucket = {
	callCount: number,
	callCountDisplay: string,
	callsWithUsage: number,
	callsWithUsageDisplay: string,
	callsWithoutUsage: number,
	callsWithoutUsageDisplay: string,
	promptTokens: number,
	promptTokensDisplay: string,
	completionTokens: number,
	completionTokensDisplay: string,
	totalTokens: number,
	totalTokensDisplay: string,
};

export type LlmProvider = LlmProvider_Serialize | LlmProvider_Deserialize;

export type LlmProvider_Deserialize = ({ Builtin: BuiltinLlmProvider_Deserialize }) & { Custom?: never } | ({ Custom: string }) & { Builtin?: never };

export type LlmProvider_Serialize = ({ Builtin: BuiltinLlmProvider_Serialize }) & { Custom?: never } | ({ Custom: string }) & { Builtin?: never };

export type LlmSegmentInput = {
	id: string,
	text: string,
};

export type LlmTaskChunkPayload<T> = {
	taskId: string,
	taskType: LlmTaskType,
	chunkIndex: number,
	totalChunks: number,
	items: T[],
};

export type LlmTaskProgressPayload = {
	taskId: string,
	taskType: LlmTaskType,
	completedChunks: number,
	totalChunks: number,
};

export type LlmTaskTextPayload = {
	taskId: string,
	taskType: LlmTaskType,
	text: string,
	delta: string,
	reset: boolean,
};

export type LlmTaskType = "polish" | "translate" | "summary";

export type LlmUsageDashboardStats = LlmUsageDashboardStats_Serialize | LlmUsageDashboardStats_Deserialize;

export type LlmUsageDashboardStats_Deserialize = {
	startedAt: string | null,
	lastUpdatedAt: string | null,
	trackingSinceDisplay: string | null,
	lastUpdatedDisplay: string | null,
	totals: DashboardUsageBucket,
	byProvider: UsageBreakdown[],
	byProviderTopRows: UsageBreakdown[],
	byProviderMaxValue: number,
	byCategory: UsageBreakdown[],
	byCategoryTopRows: UsageBreakdown[],
	byCategoryMaxValue: number,
	recentDaily: UsageTrendPoint[],
};

export type LlmUsageDashboardStats_Serialize = {
	startedAt?: string | null,
	lastUpdatedAt?: string | null,
	trackingSinceDisplay?: string | null,
	lastUpdatedDisplay?: string | null,
	totals: DashboardUsageBucket,
	byProvider: UsageBreakdown[],
	byProviderTopRows: UsageBreakdown[],
	byProviderMaxValue: number,
	byCategory: UsageBreakdown[],
	byCategoryTopRows: UsageBreakdown[],
	byCategoryMaxValue: number,
	recentDaily: UsageTrendPoint[],
};

export type OverviewStats = OverviewStats_Serialize | OverviewStats_Deserialize;

export type OverviewStats_Deserialize = {
	itemCount: number,
	itemCountDisplay: string,
	projectCount: number,
	projectCountDisplay: string,
	totalDurationSeconds: number,
	totalDurationDisplay: string,
	transcriptCharacterCount: number | null,
	transcriptCharacterCountDisplay: string | null,
	recordingCount: number,
	recordingCountDisplay: string,
	batchCount: number,
	batchCountDisplay: string,
	inboxCount: number,
	inboxCountDisplay: string,
	projectAssignedCount: number,
	projectAssignedCountDisplay: string,
	recentDailyItems: ContentTrendPoint[],
	isDeepLoaded: boolean,
};

export type OverviewStats_Serialize = {
	itemCount: number,
	itemCountDisplay: string,
	projectCount: number,
	projectCountDisplay: string,
	totalDurationSeconds: number,
	totalDurationDisplay: string,
	transcriptCharacterCount?: number | null,
	transcriptCharacterCountDisplay?: string | null,
	recordingCount: number,
	recordingCountDisplay: string,
	batchCount: number,
	batchCountDisplay: string,
	inboxCount: number,
	inboxCountDisplay: string,
	projectAssignedCount: number,
	projectAssignedCountDisplay: string,
	recentDailyItems: ContentTrendPoint[],
	isDeepLoaded: boolean,
};

export type PolishPresetId = ({ Builtin: BuiltinPolishPresetId }) & { Custom?: never } | ({ Custom: string }) & { Builtin?: never };

export type PolishedSegment = {
	id: string,
	text: string,
};

export type ProjectCreateInput = {
	name: string,
	description?: string | null,
	icon?: string | null,
	defaults: ProjectDefaultsInput,
};

export type ProjectDefaults = ProjectDefaults_Serialize | ProjectDefaults_Deserialize;

export type ProjectDefaultsInput = {
	summaryTemplateId?: string | null,
	summaryTemplate?: string | null,
	translationLanguage?: string | null,
	polishPresetId?: string | null,
	polishScenario?: string | null,
	polishContext?: string | null,
	exportFileNamePrefix?: string | null,
	enabledTextReplacementSetIds?: string[] | null,
	enabledHotwordSetIds?: string[] | null,
	enabledPolishKeywordSetIds?: string[] | null,
	enabledSpeakerProfileIds?: string[] | null,
};

export type ProjectDefaultsPatch = {
	summaryTemplateId?: string | null,
	translationLanguage?: string | null,
	polishPresetId?: string | null,
	polishScenario?: string | null,
	polishContext?: string | null,
	exportFileNamePrefix?: string | null,
	enabledTextReplacementSetIds?: string[] | null,
	enabledHotwordSetIds?: string[] | null,
	enabledPolishKeywordSetIds?: string[] | null,
	enabledSpeakerProfileIds?: string[] | null,
};

export type ProjectDefaults_Deserialize = {
	summaryTemplateId: string,
	translationLanguage: string,
	polishPresetId: string,
	polishScenario: string | null,
	polishContext: string | null,
	exportFileNamePrefix: string,
	enabledTextReplacementSetIds: string[],
	enabledHotwordSetIds: string[],
	enabledPolishKeywordSetIds: string[],
	enabledSpeakerProfileIds: string[],
};

export type ProjectDefaults_Serialize = {
	summaryTemplateId: string,
	translationLanguage: string,
	polishPresetId: string,
	polishScenario?: string | null,
	polishContext?: string | null,
	exportFileNamePrefix: string,
	enabledTextReplacementSetIds: string[],
	enabledHotwordSetIds: string[],
	enabledPolishKeywordSetIds: string[],
	enabledSpeakerProfileIds: string[],
};

export type ProjectRecord = ProjectRecord_Serialize | ProjectRecord_Deserialize;

export type ProjectRecord_Deserialize = {
	id: string,
	name: string,
	description: string,
	icon: string,
	createdAt: number,
	updatedAt: number,
	defaults: ProjectDefaults_Deserialize,
};

export type ProjectRecord_Serialize = {
	id: string,
	name: string,
	description: string,
	icon: string,
	createdAt: number,
	updatedAt: number,
	defaults: ProjectDefaults_Serialize,
};

export type ProjectRepositorySnapshot = ProjectRepositorySnapshot_Serialize | ProjectRepositorySnapshot_Deserialize;

export type ProjectRepositorySnapshot_Deserialize = {
	projects: ProjectRecord_Deserialize[],
	activeProjectId: string | null,
};

export type ProjectRepositorySnapshot_Serialize = {
	projects: ProjectRecord_Serialize[],
	activeProjectId: string | null,
};

export type ProjectUpdateInput = {
	name?: string | null,
	icon?: string | null,
	description?: string | null,
	defaults?: ProjectDefaultsPatch | null,
};

export type SpeakerLeader = {
	speakerId: string,
	label: string,
	durationSeconds: number,
	durationDisplay: string,
	segmentCount: number,
	segmentCountDisplay: string,
	itemCount: number,
	itemCountDisplay: string,
};

export type SpeakerStats = {
	annotatedItemCount: number,
	annotatedItemCountDisplay: string,
	speakerAttributedDuration: number,
	speakerAttributedDurationDisplay: string,
	identifiedSpeakerCount: number,
	identifiedSpeakerCountDisplay: string,
	anonymousSpeakerSlotCount: number,
	anonymousSpeakerSlotCountDisplay: string,
	speakerTaggedSegmentCount: number,
	speakerTaggedSegmentCountDisplay: string,
	totalSegmentCount: number,
	totalSegmentCountDisplay: string,
	totalSegmentDuration: number,
	totalSegmentDurationDisplay: string,
	identifiedDuration: number,
	identifiedDurationDisplay: string,
	anonymousDuration: number,
	anonymousDurationDisplay: string,
	segmentCoverageRatio: number,
	segmentCoverageLabel: string,
	durationCoverageRatio: number,
	durationCoverageLabel: string,
	topIdentifiedSpeakers: SpeakerLeader[],
	topIdentifiedSpeakerRows: SpeakerLeader[],
	topIdentifiedSpeakerMaxValue: number,
	isDeepLoaded: boolean,
};

export type SummarySegmentInput = {
	id: string,
	text: string,
	start: number | null,
	end: number | null,
	isFinal: boolean,
};

export type SummaryTemplateId = ({ Builtin: BuiltinSummaryTemplateId }) & { Custom?: never } | ({ Custom: string }) & { Builtin?: never };

export type TaskLedgerKind = "batchImport" | "automation" | "llmPolish" | "llmTranslate" | "llmSummary" | "recovery" | "update";

export type TaskLedgerPatch = TaskLedgerPatch_Serialize | TaskLedgerPatch_Deserialize;

export type TaskLedgerPatch_Deserialize = {
	kind?: TaskLedgerKind | null,
	status?: TaskLedgerStatus | null,
	title?: string | null,
	progress?: number | null,
	createdAt?: number | null,
	updatedAt?: number | null,
	retryable?: boolean | null,
	cancelable?: boolean | null,
	recoverable?: boolean | null,
	stage?: string | null,
	historyId?: string | null,
	projectId?: string | null,
	filePath?: string | null,
	automationRuleId?: string | null,
	sourceFingerprint?: string | null,
	errorMessage?: string | null,
	templateId?: string | null,
	targetLanguage?: string | null,
};

export type TaskLedgerPatch_Serialize = {
	kind?: TaskLedgerKind | null,
	status?: TaskLedgerStatus | null,
	title?: string | null,
	progress?: number | null,
	createdAt?: number | null,
	updatedAt?: number | null,
	retryable?: boolean | null,
	cancelable?: boolean | null,
	recoverable?: boolean | null,
	stage?: string | null,
	historyId?: string | null,
	projectId?: string | null,
	filePath?: string | null,
	automationRuleId?: string | null,
	sourceFingerprint?: string | null,
	errorMessage?: string | null,
	templateId?: string | null,
	targetLanguage?: string | null,
};

export type TaskLedgerRecord = TaskLedgerRecord_Serialize | TaskLedgerRecord_Deserialize;

export type TaskLedgerRecord_Deserialize = {
	id: string,
	kind: TaskLedgerKind,
	status: TaskLedgerStatus,
	title: string,
	progress: number,
	createdAt: number,
	updatedAt: number,
	retryable: boolean,
	cancelable: boolean,
	recoverable: boolean,
	stage: string | null,
	historyId: string | null,
	projectId: string | null,
	filePath: string | null,
	automationRuleId: string | null,
	sourceFingerprint: string | null,
	errorMessage: string | null,
	templateId: string | null,
	targetLanguage: string | null,
};

export type TaskLedgerRecord_Serialize = {
	id: string,
	kind: TaskLedgerKind,
	status: TaskLedgerStatus,
	title: string,
	progress: number,
	createdAt: number,
	updatedAt: number,
	retryable: boolean,
	cancelable: boolean,
	recoverable: boolean,
	stage?: string | null,
	historyId?: string | null,
	projectId?: string | null,
	filePath?: string | null,
	automationRuleId?: string | null,
	sourceFingerprint?: string | null,
	errorMessage?: string | null,
	templateId?: string | null,
	targetLanguage?: string | null,
};

export type TaskLedgerSnapshot = TaskLedgerSnapshot_Serialize | TaskLedgerSnapshot_Deserialize;

export type TaskLedgerSnapshot_Deserialize = {
	version: number,
	updatedAt: number | null,
	tasks: TaskLedgerRecord_Deserialize[],
};

export type TaskLedgerSnapshot_Serialize = {
	version: number,
	updatedAt: number | null,
	tasks: TaskLedgerRecord_Serialize[],
};

export type TaskLedgerStatus = "pending" | "running" | "cancelRequested" | "failed" | "recoverable" | "interrupted" | "cancelled" | "succeeded";

export type TranscriptSummaryResult = {
	templateId: string,
	content: string,
};

export type TranslatedSegment = {
	id: string,
	translation: string,
};

export type UsageBreakdown = {
	key: string,
	label: string,
	stats: DashboardUsageBucket,
	value: number,
	valueDisplay: string,
};

export type UsageTrendPoint = {
	date: string,
	dateLabel: string,
} & DashboardUsageBucket;
