export {
  appendOrMergeSuccessNotification,
  applyRetryBlockedResults,
  applyRetryFailureResults,
  applyRuntimeBlockState,
  applyRuntimeFailureState,
  applyRuntimeQueuedState,
  applyRuntimeReplaceResults,
  applyTaskSettledState,
  buildRetryBlockedEntry,
  buildRetryFailureEntry,
  deriveRuntimeState,
  getAutomationFailureNotificationId,
  getRetryBlockedMessage,
  getRetryFailureMessage,
  getUniqueFilePaths,
  hasRetryableFailures,
  rebuildRuntimeStates,
  removeRuleNotifications,
  upsertFailureNotification,
  type AutomationNotificationKind,
  type AutomationSessionNotification,
} from '../services/automation/automationSessionState';
